export {default as Header} from "./Header/header" 
export {default as Container} from "./Container/container" 
export {default as Footer} from "./Footer/footer" 
export {default as Hero} from "./Container/Hero/Hero" 
export {default as MostPopular} from "./Container/MostPopular/MostPopular";
export {default as GamingLibrary} from "../components/Container/GamingLibrary/GamingLibrary";
export {default as Card} from "./Container/Card/Card";
export {default as SectionHeader} from "./Container/SectionHeader/SectionHeader";
export {default as SectionWrapper} from "./Container/SectionWrapper/SectionWrapper";
export {default as GamingLibraryCards} from "./Container/GamingLibraryCards/GamingLibraryCards";
export {default as PrimaryButtons} from "./Container/Buttons/Buttons";
export {SecondryButtons as SecondryButtons} from "./Container/Buttons/Buttons";
